name: "build: extensions"
on: [push]

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build resolver
        run: pnpm run build:resolver

      - name: Build extension
        run: pnpm run build:extension
      
      - name: Upload extension
        uses: actions/upload-artifact@v3
        with:
          name: voltaire-resolver-extension
          path: packages/chrome/dist/
